workflows:
  ios-workflow:
    name: Playcondominio
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: playcondominio.comapp

    scripts:
      - name: Clean Pods
        script: |
          rm -rf Pods
          rm -rf Podfile.lock

      - name: Install Pods
        script: |
          pod install --repo-update

      - name: Apply Code Signing
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "playcondominio.xcworkspace" \
            --scheme "playcondominio"

    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
